### ISSUE TITLE
[SOLVED] failed to run custom build command for nexus-network v0.4.0

### ISSUE THREAD

**Issue by shipper96** [nexus-xyz/network-api#111]
I installed protoc, it's libprotoc 3.6.1. But when run the command, it's still error: 

error: failed to run custom build command for `nexus-network v0.4.0 (/root/.nexus/network-api/clients/cli)`

Caused by:
  process didn't exit successfully: `/root/.nexus/network-api/clients/cli/target/release/build/nexus-network-01d0541f667d1829/build-script-build` (exit status: 1)
  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: Unknown flag: --experimental_allow_proto3_optional\n" }

**Comment by susah-diutarakan** [comment]
Update protobuf to latest version 29.1 
your protobuf still old version didn't support the flag

**Comment by shipper96** [comment]
then how to upgrade to lastest version?

**Comment by susah-diutarakan** [comment]
PROTOC_VERSION=29.1

curl -LO https://github.com/protocolbuffers/protobuf/releases//download/v$PROTOC_VERSION/protoc-$PROTOC_VERSION-linux-x86_64.zip

unzip protoc-$PROTOC_VERSION-linux-x86_64.zip -d $HOME/.local

export PATH="${HOME}/.local/bin":${PATH}

rm protoc-protoc-$PROTOC_VERSION-linux-x86_64.zip

protoc --version

make sure it show v 29.1

then rerun nexus

source :
https://stackoverflow.com/questions/79263735/install-protobuf-on-ubuntu-update-the-home-but-still-protoc-version-points-to

**Comment by shipper96** [comment]
same, the version compiler still 3.6.1.

In the source, the guy asked the same question: [install protobuf new version but still points to the old version](https://stackoverflow.com/questions/79263735/install-protobuf-on-ubuntu-update-the-home-but-still-protoc-version-points-to)

**Comment by vinhhathacha** [comment]
sudo add-apt-repository ppa:maarten-fonville/protobuf
sudo apt update
sudo apt install protobuf-compiler libprotobuf-dev

**Comment by shipper96** [comment]
didn't work. The protoc still 3.6.1 version.

It's error when run sudo add-apt-repository ppa:maarten-fonville/protobuf and sudo apt update at this bold line: 


Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal InRelease
Ign:3 http://ppa.launchpad.net/maarten-fonville/protobuf/ubuntu focal InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
**Err:5 http://ppa.launchpad.net/maarten-fonville/protobuf/ubuntu focal Release**
  404  Not Found [IP: xxx.xxx.190.80 80]
Hit:6 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/maarten-fonville/protobuf/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by susah-diutarakan** [comment]
> same, the version compiler still 3.6.1.
> 
> In the source, the guy asked the same question: [install protobuf new version but still points to the old version](https://stackoverflow.com/questions/79263735/install-protobuf-on-ubuntu-update-the-home-but-still-protoc-version-points-to)

Type this command

export PATH="${HOME}/.local/bin":${PATH}    --> Press Enter
protoc --version             --> press enter

if show v29.1 then run this command

curl https://cli.nexus.xyz/ | sh 

if no error mean working well
don't forget to update with your prover id you using on web

**Comment by shipper96** [comment]
> curl https://cli.nexus.xyz/ | sh

of course I run export PATH="${HOME}/.local/bin":${PATH} as the guy in stackoverflow. 

and me and that guy had same issues: the protoc compiler still show v3.6.1.

**Comment by susah-diutarakan** [comment]
> $HOME/.local

try this

cd $HOME/.local
protoc --version 

run from there to compile the nexus cli

**Comment by shipper96** [comment]
> > $HOME/.local
> 
> try this
> 
> cd $HOME/.local protoc --version
> 
> run from there to compile the nexus cli

from $HOME/.local, I saw bin include readme.txt share 

but the version still is 3.6.1

**Comment by shipper96** [comment]
> > same, the version compiler still 3.6.1.
> > In the source, the guy asked the same question: [install protobuf new version but still points to the old version](https://stackoverflow.com/questions/79263735/install-protobuf-on-ubuntu-update-the-home-but-still-protoc-version-points-to)
> 
> Type this command
> 
> export PATH="${HOME}/.local/bin":${PATH} --> Press Enter protoc --version --> press enter
> 
> if show v29.1 then run this command
> 
> curl https://cli.nexus.xyz/ | sh
> 
> if no error mean working well don't forget to update with your prover id you using on web

I found the way. Just remove the old version using it:

sudo apt-get remove protobuf-compiler

**Comment by hanadiana258** [comment]
> > > same, the version compiler still 3.6.1.
> > > In the source, the guy asked the same question: [install protobuf new version but still points to the old version](https://stackoverflow.com/questions/79263735/install-protobuf-on-ubuntu-update-the-home-but-still-protoc-version-points-to)
> > 
> > 
> > Type this command
> > export PATH="${HOME}/.local/bin":${PATH} --> Press Enter protoc --version --> press enter
> > if show v29.1 then run this command
> > curl https://cli.nexus.xyz/ | sh
> > if no error mean working well don't forget to update with your prover id you using on web
> 
> I found the way. Just remove the old version using it:
> 
> sudo apt-get remove protobuf-compiler
> 
> then run your commands and it's working

already remove and reinstall protobuff still error
version show 3.6.1

**Comment by shipper96** [comment]
> PROTOC_VERSION=29.1
> 
> curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v29.1/protoc-29.1-linux-x86_64.zip
> 
> unzip protoc-$PROTOC_VERSION-linux-x86_64.zip -d $HOME/.local
> 
> export PATH="${HOME}/.local/bin":${PATH}
> 
> rm protoc-protoc-$PROTOC_VERSION-linux-x86_64.zip
> 
> protoc --version
> 
> make sure it show v 29.1
> 
> then rerun nexus
> 
> source : https://stackoverflow.com/questions/79263735/install-protobuf-on-ubuntu-update-the-home-but-still-protoc-version-points-to

remove old protoc (remember update using sudo apt command) then run follow this guide.

**Comment by umair-mirza** [comment]
After I run this command:

`curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v29.1/protoc-29.1-linux-x86_64.zip`

and then this command:

`unzip protoc-$PROTOC_VERSION-linux-x86_64.zip -d $HOME/.local`

I get this error:
```
unzip:  cannot find zipfile directory in one of protoc--linux-x86_64.zip or
        protoc--linux-x86_64.zip.zip, and cannot find protoc--linux-x86_64.zip.ZIP, period.
```

**Comment by susah-diutarakan** [comment]
> After I run this command:
> 
> `curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v29.1/protoc-29.1-linux-x86_64.zip`
> 
> and then this command:
> 
> `unzip protoc-$PROTOC_VERSION-linux-x86_64.zip -d $HOME/.local`
> 
> I get this error:
> 
> ```
> unzip:  cannot find zipfile directory in one of protoc--linux-x86_64.zip or
>         protoc--linux-x86_64.zip.zip, and cannot find protoc--linux-x86_64.zip.ZIP, period.
> ```

You type wrong command, try this

unzip protoc-29.1-linux-x86_64.zip -d $HOME/.local

**Comment by shipper96** [comment]
> After I run this command:
> 
> `curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v29.1/protoc-29.1-linux-x86_64.zip`
> 
> and then this command:
> 
> `unzip protoc-$PROTOC_VERSION-linux-x86_64.zip -d $HOME/.local`
> 
> I get this error:
> 
> ```
> unzip:  cannot find zipfile directory in one of protoc--linux-x86_64.zip or
>         protoc--linux-x86_64.zip.zip, and cannot find protoc--linux-x86_64.zip.ZIP, period.
> ```

replace $PROTOC_VERSION = your downloaded version.

**Comment by Giangr2812** [comment]
> > > tương tự, trình biên dịch phiên bản vẫn là 3.6.1. 
> > > Trong nguồn, anh chàng đã hỏi cùng một câu hỏi: [cài đặt protobuf phiên bản mới nhưng vẫn trỏ đến phiên bản cũ](https://stackoverflow.com/questions/79263735/install-protobuf-on-ubuntu-update-the-home-but-still-protoc-version-points-to)
> > 
> > 
> > Nhập lệnh này
> > export PATH="${HOME}/.local/bin":${PATH} --> Nhấn Enter protoc --version --> nhấn enter
> > nếu hiển thị v29.1 thì chạy lệnh này
> > curl https://cli.nexus.xyz/ | sh
> > nếu không có lỗi có nghĩa là hoạt động tốt đừng quên cập nhật bằng id prover mà bạn đang sử dụng trên web
> 
> Tôi đã tìm ra cách. Chỉ cần xóa phiên bản cũ bằng cách sử dụng nó:
> 
> sudo apt-get xóa trình biên dịch protobuf
> 
> sau đó chạy lệnh của bạn và nó hoạt động

tôi dùng macos thì làm như thế nào

**Comment by chienlvm** [comment]
> > > > tương tự, trình biên dịch phiên bản vẫn là 3.6.1.
> > > > Trong nguồn, anh chàng đã hỏi cùng một câu hỏi: [cài đặt protobuf phiên bản mới nhưng vẫn trỏ đến phiên bản cũ](https://stackoverflow.com/questions/79263735/install-protobuf-on-ubuntu-update-the-home-but-still-protoc-version-points-to)
> > > 
> > > 
> > > Nhập lệnh này
> > > export PATH="${HOME}/.local/bin":${PATH} --> Nhấn Enter protoc --version --> nhấn enter
> > > nếu hiển thị v29.1 thì chạy lệnh này
> > > curl https://cli.nexus.xyz/ | sh
> > > nếu không có lỗi có nghĩa là hoạt động tốt đừng quên cập nhật bằng id prover mà bạn đang sử dụng trên web
> > 
> > 
> > Tôi đã tìm ra cách. Chỉ cần xóa phiên bản cũ bằng cách sử dụng nó:
> > sudo apt-get xóa trình biên dịch protobuf
> > sau đó chạy lệnh của bạn và nó hoạt động
> 
> tôi dùng macos thì làm như thế nào

Using chatGPT to transfer linux commands to macOS

**Comment by Anshumanspams** [comment]
![Screenshot (2)](https://github.com/user-attachments/assets/e6278bd7-4ff5-49da-a01c-e047e67ba891)
still getting this error again and again

**Comment by tommien86** [comment]
> ![Screenshot (2)](https://private-user-images.githubusercontent.com/186760532/394889319-e6278bd7-4ff5-49da-a01c-e047e67ba891.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5OTEwNzEsIm5iZiI6MTczMzk5MDc3MSwicGF0aCI6Ii8xODY3NjA1MzIvMzk0ODg5MzE5LWU2Mjc4YmQ3LTRmZjUtNDlkYS1hMDFjLWUwNDdlNjdiYTg5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwODA2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MmQ2OGI5MGZkZDc2Yjc0NTQ0MmVhYTQ0OGNkZWYzNGI2OWViODIwMjIxOTE0Y2U5NTI0MTJmMGFiNWExMzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yrIvYP9ePWC89luprfUy50_O_mz7HMcBgoT38DDjELM) still getting this error again and again even my version is 29.1
> 
> ![image](https://private-user-images.githubusercontent.com/186760532/394890877-492c3fa8-d4d9-4292-99ac-4d613d280f8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5OTEwNzEsIm5iZiI6MTczMzk5MDc3MSwicGF0aCI6Ii8xODY3NjA1MzIvMzk0ODkwODc3LTQ5MmMzZmE4LWQ0ZDktNDI5Mi05OWFjLTRkNjEzZDI4MGY4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQwODA2MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzc5NDZjOWFjY2Y1MzQyMzVmMjkzYjgxNDFkYWIzZDNhYWU5N2FjMmE5N2IyYjQ4ZmYzZjFlOWU2ZTZlYTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dc5Io7l49S0S9RXLDxEKqiMc9AK4GXvx49UlYS8pLhM)

decided?
