### ISSUE TITLE
failed to run custom build command for `openssl-sys v0.9.103`

### ISSUE THREAD

**Issue by duck889988** [nexus-xyz/network-api#126]
failed to run custom build command for `openssl-sys v0.9.103`

any idea how to solve this?

![image](https://github.com/user-attachments/assets/e226901c-92d8-498b-b83c-03c8c92c2b75)

**Comment by shipper96** [comment]
did you try solution #111?

**Comment by duck889988** [comment]
> did you try solution #111?

hi thanks for the advice, is solve.

**Comment by duck889988** [comment]
solved

**Comment by Tanniks** [comment]
> solved
Same.How solv?Thanks

**Comment by Tanniks** [comment]
its useful for me on ubuntu:
 sudo apt install pkg-config
 sudo apt-get install libudev-dev libssl-dev
