### ISSUE TITLE
warning: nexus-network@0.4.0: Failed to run protoc: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by Popelnyuk** [nexus-xyz/network-api#162]
The following warnings were emitted during compilation:

warning: nexus-network@0.4.0: Failed to run protoc: No such file or directory (os error 2)

error: failed to run custom build command for `nexus-network v0.4.0 (/home/kryptonetc/.nexus/network-api/clients/cli)`

Caused by:
  process didn't exit successfully: `/home/kryptonetc/.nexus/network-api/clients/cli/target/release/build/nexus-network-01d0541f667d1829/build-script-build` (exit status: 1)
  --- stdout
  cargo:warning=Failed to run protoc: No such file or directory (os error 2)

  --- stderr
  Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
warning: build failed, waiting for other jobs to finish...

**Comment by mddsix** [comment]
how to fix it?

**Comment by Popelnyuk** [comment]
It's decided:
sudo apt update
sudo apt install protobuf-compiler
