### ISSUE TITLE
PAGE LOADING FAILURE

### ISSUE THREAD

**Issue by Cephas0205** [nexus-xyz/network-api#191]
Over the days I started running nides, it's been issues here and there.
One of it is that the page fails to load. Recently I've been trying to connect the page, it's not working.
It's been issues here and there.

**Comment by collinjackson** [comment]
Thanks for the report. Server connectivity is being worked on.

Feel free to reopen new issues but please include error logs, screenshots, etc. so we can pin down the issue.
