### ISSUE TITLE
Merging Error

### ISSUE THREAD

**Issue by 0xCipherNinja** [nexus-xyz/network-api#34]
root@MSI:~# curl https://cli.nexus.xyz/ | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   893  100   893    0     0   2821      0 --:--:-- --:--:-- --:--:--  2817
rustc 1.82.0 (f6e511eec 2024-10-15)
Do you agree to the Nexus Beta Terms of Use (https://nexus.xyz/terms-of-use)? (Y/n) Y
/root/.nexus/network-api exists. Updating.
Updating f7fe621..d9507aa
error: Your local changes to the following files would be overwritten by merge:
        clients/cli/Cargo.lock
Please commit your changes or stash them before you merge.
Aborting
    Finished `release` profile [optimized] target(s) in 2.09s
     Running `target/release/prover beta.orchestrator.nexus.xyz`
Connecting to wss://beta.orchestrator.nexus.xyz:443/prove...
Connected.
Your assigned prover identifier is seaborgium-piciform-76.
Received a 21060 byte program to prove with 3 bytes of input
Program trace is 196 steps. Proving 10 steps starting at 19...
Proved step 19 at 5.45 proof cycles/sec.
Proved step 20 at 3.94 proof cycles/sec.
Proved step 21 at 3.33 proof cycles/sec.

**Comment by collinjackson** [comment]
Fixed
