### ISSUE TITLE
Clarify dependencies for installation on Ubuntu

### ISSUE THREAD

**Issue by danielmarinq** [nexus-xyz/network-api#9]
I experimented with running `curl https://cli.nexus.xyz | sh` on a fresh E2 GCP instance running Debian Ubuntu, but faced a few challenges. First, it seems that the CLI requires `build-essential`, `pkg-config`, `libssl-dev` (OpenSSL),  and `git` as dependencies.

So installation on Ubuntu would look like this:

1. `sudo apt update`
2. `sudo apt upgrade`
3. `sudo apt install build-essential pkg-config libssl-dev git-all`
4. `curl https://cli.nexus.xyz | sh`

We may want to add this to [docs.nexus.xyz](https://docs.nexus.xyz).

**Comment by Gmhaxx** [comment]
Nice its working! 
![image](https://github.com/user-attachments/assets/532b36ce-4be1-4f25-a735-1ed0185d5d8e)

**Comment by collinjackson** [comment]
Fixed in #18
